name: ruff

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      - name: Install dependencies
        run: |
          pip install .
      - name: Format
        run: |
          ruff format . --check
      - name: Lint
        run: |
          ruff check .